packages:
  - packages/*

allowBuilds:
  esbuild: true
  protobufjs: true
  "seyfert@https://codeload.github.com/tiramisulabs/seyfert/tar.gz/a85c842c579d2055a446e3c65524e783962c85a6": true

minimumReleaseAgeExclude:
  - seyfert

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - seyfert
