packages:
  - packages/*

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  protobufjs: true
  seyfert: true
  seyfert@https://codeload.github.com/tiramisulabs/seyfert/tar.gz/4aee9b68314f38b193d3cb2a3ac27c51b0eae0af: true

minimumReleaseAgeExclude:
  - seyfert

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - seyfert
