import type { RouteMatcher } from './rest';

export const Routes = {
	ban: { method: 'PUT', route: '/guilds/:guildId/bans/:userId' },
	unban: { method: 'DELETE', route: '/guilds/:guildId/bans/:userId' },
	kick: { method: 'DELETE', route: '/guilds/:guildId/members/:userId' },
	editMember: { method: 'PATCH', route: '/guilds/:guildId/members/:userId' },
	addRole: { method: 'PUT', route: '/guilds/:guildId/members/:userId/roles/:roleId' },
	removeRole: { method: 'DELETE', route: '/guilds/:guildId/members/:userId/roles/:roleId' },
	createMessage: { method: 'POST', route: '/channels/:channelId/messages' },
	editMessage: { method: 'PATCH', route: '/channels/:channelId/messages/:messageId' },
	deleteMessage: { method: 'DELETE', route: '/channels/:channelId/messages/:messageId' },
	bulkDeleteMessages: { method: 'POST', route: '/channels/:channelId/messages/bulk-delete' },
	createDm: { method: 'POST', route: '/users/@me/channels' },
	createRole: { method: 'POST', route: '/guilds/:guildId/roles' },
	editRole: { method: 'PATCH', route: '/guilds/:guildId/roles/:roleId' },
	deleteRole: { method: 'DELETE', route: '/guilds/:guildId/roles/:roleId' },
	editGuild: { method: 'PATCH', route: '/guilds/:guildId' },
	fetchBan: { method: 'GET', route: '/guilds/:guildId/bans/:userId' },
	editChannelPermissions: { method: 'PUT', route: '/channels/:channelId/permissions/:overwriteId' },
	deleteChannelPermission: { method: 'DELETE', route: '/channels/:channelId/permissions/:overwriteId' },
	createChannel: { method: 'POST', route: '/guilds/:guildId/channels' },
	deleteChannel: { method: 'DELETE', route: '/channels/:channelId' },
	createThread: { method: 'POST', route: '/channels/:channelId/threads' },
	addReaction: { method: 'PUT', route: '/channels/:channelId/messages/:messageId/reactions/:emoji/@me' },
	removeOwnReaction: { method: 'DELETE', route: '/channels/:channelId/messages/:messageId/reactions/:emoji/@me' },
	removeUserReaction: { method: 'DELETE', route: '/channels/:channelId/messages/:messageId/reactions/:emoji/:userId' },
	removeAllReactions: { method: 'DELETE', route: '/channels/:channelId/messages/:messageId/reactions' },
	removeEmojiReactions: { method: 'DELETE', route: '/channels/:channelId/messages/:messageId/reactions/:emoji' },
	listReactions: { method: 'GET', route: '/channels/:channelId/messages/:messageId/reactions/:emoji' },
	fetchChannel: { method: 'GET', route: '/channels/:channelId' },
	fetchMember: { method: 'GET', route: '/guilds/:guildId/members/:userId' },
	fetchGuild: { method: 'GET', route: '/guilds/:guildId' },
	fetchUser: { method: 'GET', route: '/users/:userId' },
	fetchOriginalResponse: { method: 'GET', route: '/webhooks/:applicationId/:interactionToken/messages/@original' },
	editOriginalResponse: { method: 'PATCH', route: '/webhooks/:applicationId/:interactionToken/messages/@original' },
	deleteOriginalResponse: { method: 'DELETE', route: '/webhooks/:applicationId/:interactionToken/messages/@original' },
	fetchWebhookMessage: { method: 'GET', route: '/webhooks/:applicationId/:interactionToken/messages/:messageId' },
	editWebhookMessage: { method: 'PATCH', route: '/webhooks/:applicationId/:interactionToken/messages/:messageId' },
	deleteWebhookMessage: { method: 'DELETE', route: '/webhooks/:applicationId/:interactionToken/messages/:messageId' },
	followup: { method: 'POST', route: '/webhooks/:applicationId/:interactionToken' },
	interactionCallback: { method: 'POST', route: '/interactions/:id/:token/callback' },
	listChannelWebhooks: { method: 'GET', route: '/channels/:channelId/webhooks' },
	createWebhook: { method: 'POST', route: '/channels/:channelId/webhooks' },
	fetchMessages: { method: 'GET', route: '/channels/:channelId/messages' },
	fetchMessage: { method: 'GET', route: '/channels/:channelId/messages/:messageId' },
	fetchRoles: { method: 'GET', route: '/guilds/:guildId/roles' },
	fetchChannels: { method: 'GET', route: '/guilds/:guildId/channels' },
	fetchBans: { method: 'GET', route: '/guilds/:guildId/bans' },
	fetchPins: { method: 'GET', route: '/channels/:channelId/messages/pins' },
	editChannel: { method: 'PATCH', route: '/channels/:channelId' },
	createInvite: { method: 'POST', route: '/channels/:channelId/invites' },
	pinMessage: { method: 'PUT', route: '/channels/:channelId/messages/pins/:messageId' },
	unpinMessage: { method: 'DELETE', route: '/channels/:channelId/messages/pins/:messageId' },
	fetchArchivedThreads: { method: 'GET', route: '/channels/:channelId/threads/archived/:type' },
	startThreadFromMessage: { method: 'POST', route: '/channels/:channelId/messages/:messageId/threads' },
	crosspostMessage: { method: 'POST', route: '/channels/:channelId/messages/:messageId/crosspost' },
	triggerTyping: { method: 'POST', route: '/channels/:channelId/typing' },
	createEmoji: { method: 'POST', route: '/guilds/:guildId/emojis' },
	fetchEmojis: { method: 'GET', route: '/guilds/:guildId/emojis' },
	fetchEmoji: { method: 'GET', route: '/guilds/:guildId/emojis/:emojiId' },
	editEmoji: { method: 'PATCH', route: '/guilds/:guildId/emojis/:emojiId' },
	deleteEmoji: { method: 'DELETE', route: '/guilds/:guildId/emojis/:emojiId' },
	listChannelInvites: { method: 'GET', route: '/channels/:channelId/invites' },
	listGuildInvites: { method: 'GET', route: '/guilds/:guildId/invites' },
	fetchInvite: { method: 'GET', route: '/invites/:code' },
	deleteInvite: { method: 'DELETE', route: '/invites/:code' },
	bulkBan: { method: 'POST', route: '/guilds/:guildId/bulk-bans' },
	fetchAutoModRules: { method: 'GET', route: '/guilds/:guildId/auto-moderation/rules' },
	createAutoModRule: { method: 'POST', route: '/guilds/:guildId/auto-moderation/rules' },
	fetchAutoModRule: { method: 'GET', route: '/guilds/:guildId/auto-moderation/rules/:ruleId' },
	editAutoModRule: { method: 'PATCH', route: '/guilds/:guildId/auto-moderation/rules/:ruleId' },
	deleteAutoModRule: { method: 'DELETE', route: '/guilds/:guildId/auto-moderation/rules/:ruleId' },
	addThreadMember: { method: 'PUT', route: '/channels/:channelId/thread-members/:userId' },
	removeThreadMember: { method: 'DELETE', route: '/channels/:channelId/thread-members/:userId' },
	listThreadMembers: { method: 'GET', route: '/channels/:channelId/thread-members' },
	fetchThreadMember: { method: 'GET', route: '/channels/:channelId/thread-members/:userId' },
	fetchActiveThreads: { method: 'GET', route: '/guilds/:guildId/threads/active' },
	endPoll: { method: 'POST', route: '/channels/:channelId/polls/:messageId/expire' },
	getPollAnswerVoters: { method: 'GET', route: '/channels/:channelId/polls/:messageId/answers/:answerId' },
	createSticker: { method: 'POST', route: '/guilds/:guildId/stickers' },
	fetchStickers: { method: 'GET', route: '/guilds/:guildId/stickers' },
	fetchSticker: { method: 'GET', route: '/guilds/:guildId/stickers/:stickerId' },
	editSticker: { method: 'PATCH', route: '/guilds/:guildId/stickers/:stickerId' },
	deleteSticker: { method: 'DELETE', route: '/guilds/:guildId/stickers/:stickerId' },
	fetchScheduledEvents: { method: 'GET', route: '/guilds/:guildId/scheduled-events' },
	createScheduledEvent: { method: 'POST', route: '/guilds/:guildId/scheduled-events' },
	fetchScheduledEvent: { method: 'GET', route: '/guilds/:guildId/scheduled-events/:eventId' },
	deleteScheduledEvent: { method: 'DELETE', route: '/guilds/:guildId/scheduled-events/:eventId' },
	fetchGuildTemplate: { method: 'GET', route: '/guilds/templates/:code' },
	listGuildTemplates: { method: 'GET', route: '/guilds/:guildId/templates' },
	createGuildTemplate: { method: 'POST', route: '/guilds/:guildId/templates' },
	listGuildSoundboardSounds: { method: 'GET', route: '/guilds/:guildId/soundboard-sounds' },
	listDefaultSoundboardSounds: { method: 'GET', route: '/soundboard-default-sounds' },
	createStageInstance: { method: 'POST', route: '/stage-instances' },
	fetchStageInstance: { method: 'GET', route: '/stage-instances/:channelId' },
	deleteStageInstance: { method: 'DELETE', route: '/stage-instances/:channelId' },
	fetchAuditLogs: { method: 'GET', route: '/guilds/:guildId/audit-logs' },
	fetchWebhook: { method: 'GET', route: '/webhooks/:webhookId' },
	fetchWebhookToken: { method: 'GET', route: '/webhooks/:webhookId/:webhookToken' },
	editWebhook: { method: 'PATCH', route: '/webhooks/:webhookId' },
	editWebhookToken: { method: 'PATCH', route: '/webhooks/:webhookId/:webhookToken' },
	deleteWebhook: { method: 'DELETE', route: '/webhooks/:webhookId' },
	deleteWebhookToken: { method: 'DELETE', route: '/webhooks/:webhookId/:webhookToken' },
	listGuildWebhooks: { method: 'GET', route: '/guilds/:guildId/webhooks' },
} as const satisfies Record<string, RouteMatcher>;

/**
 * Coverage checklist for every {@link Routes} entry. `handled` = registerWorldDefaults installs a
 * stateful interceptor; `synthetic` = intentionally left to the fail-loud synthetic fallback. The
 * `satisfies Record<keyof typeof Routes, …>` makes adding a route without classifying it a compile
 * error — closing the "added a route, forgot the handler" gap the maintenance map tracked by hand.
 */
export const ROUTE_COVERAGE = {
	ban: 'handled',
	unban: 'handled',
	kick: 'handled',
	editMember: 'handled',
	addRole: 'handled',
	removeRole: 'handled',
	createMessage: 'handled',
	editMessage: 'handled',
	deleteMessage: 'handled',
	bulkDeleteMessages: 'handled',
	createDm: 'handled',
	createRole: 'handled',
	editRole: 'handled',
	deleteRole: 'handled',
	editGuild: 'handled',
	fetchBan: 'handled',
	editChannelPermissions: 'handled',
	deleteChannelPermission: 'handled',
	createChannel: 'handled',
	deleteChannel: 'handled',
	createThread: 'handled',
	addReaction: 'handled',
	removeOwnReaction: 'handled',
	removeUserReaction: 'handled',
	removeAllReactions: 'handled',
	removeEmojiReactions: 'handled',
	listReactions: 'handled',
	fetchChannel: 'handled',
	fetchMember: 'handled',
	fetchGuild: 'handled',
	fetchUser: 'handled',
	fetchOriginalResponse: 'handled',
	editOriginalResponse: 'handled',
	deleteOriginalResponse: 'handled',
	fetchWebhookMessage: 'handled',
	editWebhookMessage: 'handled',
	deleteWebhookMessage: 'handled',
	followup: 'handled',
	interactionCallback: 'handled',
	listChannelWebhooks: 'handled',
	createWebhook: 'handled',
	fetchMessages: 'handled',
	fetchMessage: 'handled',
	fetchRoles: 'handled',
	fetchChannels: 'handled',
	fetchBans: 'handled',
	fetchPins: 'handled',
	editChannel: 'handled',
	createInvite: 'handled',
	pinMessage: 'handled',
	unpinMessage: 'handled',
	fetchArchivedThreads: 'handled',
	startThreadFromMessage: 'handled',
	crosspostMessage: 'synthetic',
	triggerTyping: 'handled',
	createEmoji: 'handled',
	fetchEmojis: 'handled',
	fetchEmoji: 'handled',
	editEmoji: 'handled',
	deleteEmoji: 'handled',
	listChannelInvites: 'handled',
	listGuildInvites: 'handled',
	fetchInvite: 'handled',
	deleteInvite: 'handled',
	bulkBan: 'handled',
	fetchAutoModRules: 'handled',
	createAutoModRule: 'handled',
	fetchAutoModRule: 'handled',
	editAutoModRule: 'handled',
	deleteAutoModRule: 'handled',
	addThreadMember: 'handled',
	removeThreadMember: 'handled',
	listThreadMembers: 'handled',
	fetchThreadMember: 'handled',
	fetchActiveThreads: 'handled',
	endPoll: 'handled',
	getPollAnswerVoters: 'handled',
	createSticker: 'handled',
	fetchStickers: 'handled',
	fetchSticker: 'handled',
	editSticker: 'handled',
	deleteSticker: 'handled',
	fetchScheduledEvents: 'handled',
	createScheduledEvent: 'handled',
	fetchScheduledEvent: 'handled',
	deleteScheduledEvent: 'handled',
	fetchGuildTemplate: 'handled',
	listGuildTemplates: 'handled',
	createGuildTemplate: 'handled',
	listGuildSoundboardSounds: 'handled',
	listDefaultSoundboardSounds: 'handled',
	createStageInstance: 'handled',
	fetchStageInstance: 'handled',
	deleteStageInstance: 'handled',
	fetchAuditLogs: 'handled',
	fetchWebhook: 'handled',
	fetchWebhookToken: 'handled',
	editWebhook: 'handled',
	editWebhookToken: 'handled',
	deleteWebhook: 'handled',
	deleteWebhookToken: 'handled',
	listGuildWebhooks: 'handled',
} as const satisfies Record<keyof typeof Routes, 'handled' | 'synthetic'>;

export const WEBHOOK_MESSAGE_ROUTE = /\/webhooks\/[^/]+\/[^/]+\/messages\/[^/]+$/;
export const FOLLOWUP_ROUTE = /\/webhooks\/[^/]+\/[^/]+$/;
export const CHANNEL_MESSAGE_POST = /\/channels\/[^/]+\/messages$/;
export const WEBHOOK_EXECUTE_POST = /\/webhooks\/wh-[^/]+\/[^/]+$/;
